## Spring Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz_mail_demo
    username: root
    password:

 ## Quartz Properties
  quartz:
    job-store-type: jdbc
    properties:
      quartz:
        threadPool:
          threadCount:5:


 ## Mail Properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: *********************** (From_email_Id)
    password: ************ 
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
